### ISSUE TITLE
Roadmap to V4.1!

### ISSUE THREAD

**Issue by GilbertGobbels** [GilbertGobbels/GAwesomeBot#115]
**Must have:**
- [x] Replace domains in extensions - Completed as of #122 
- [x] Updating system in place - Worked on by Gilbert
- [ ] A better boot - Working on it (Vlad)

**Issues that need to be fixed:**

- [ ] #103 
- [ ] #75 
- [ ] #88 
- [x] #105 
- [x] #93 
- [x] #120 

**Would be nice to have:**

- [x] Have some form of express clustering
- [x] Improve extension permissions
- [x] Minor improvements to embedding/web interface - Embeds will get a massive improvement (Vlad)
- [x] New package.json - #117

**Comment by KingDGrizzle** [comment]
*Remove domains all along*

**Comment by KingDGrizzle** [comment]
I'm taking any domain removal, embed improvements, and *possibly* express clusters (*if I'm getting an example, that is*)

A better boot: I was thinking of using the shardReady event once again, and just output a log message saying "A shard just connected", and give more info after the ready event triggered

**Comment by oskikiboy** [comment]
What about a way to change the boot text from maintainer dashboard instead of it saying AwesomeBot all the time. maintainers could type text into the dashboard that would apply on the next reboot.

**Comment by KingDGrizzle** [comment]
#122 for Removal of Domains

**Comment by cryptochrome** [comment]
I think you should add an updater for self-hosters :)

**Comment by KingDGrizzle** [comment]
Its being worked on

**Comment by KingDGrizzle** [comment]
I've also gotten alot of "feedback" for the embeds, and what we can improve. As such, I will take that task and WILL improve them all!

**Comment by Honzzzox** [comment]
test

**Comment by Honzzzox** [comment]
k

**Comment by Honzzzox** [comment]
i like this Github bot ^^^^

**Comment by KingDGrizzle** [comment]
While removing domains is a fantastic idea, removing it from extensions is a bad idea. It can leave the bot in a bootloop which then the hoster has to rectify. As such, we'll keep domains **in extensions**, but no-where else

**Comment by KingDGrizzle** [comment]
Progress is being made, and.. *Spoiler..* Atleast 2 or more of the events will get a nice pretty embed.. 👀

**Comment by oskikiboy** [comment]
I Might be able to add the custom ascii art myself. See above ^.

**Comment by ffxhand** [comment]
RIP this issue

**Comment by Gilbert142** [comment]
Transferred to #184
